services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 'yassir'
      POSTGRES_DB: 'wrm'
      POSTGRES_PASSWORD: 'User_Password'
    ports:
      - "5431:5431"
    command: ["postgres", "-p", "5431"]

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'axelyoucode@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_LISTEN_PORT: '5050'
    ports:
      - "5050:5050"
