services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 'yassir'
      POSTGRES_DB: 'wrm'
      POSTGRES_PASSWORD: 'User_Password'
    ports:
      - "5431:5431"
    command: ["postgres", "-p", "5431"]

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'axelyoucode@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_LISTEN_PORT: '5050'
    ports:
      - "5050:5050"


  postgres-uat:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: 'uat_user'
      POSTGRES_DB: 'uat_db'
      POSTGRES_PASSWORD: 'uat_password'
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]

  pgadmin-uat:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'uat_admin@yourdomain.com'
      PGADMIN_DEFAULT_PASSWORD: 'uat_admin_password'
      PGADMIN_LISTEN_PORT: '5051'
    ports:
      - "5051:5051"



