waiting-list:
  default-algorithm: FIFO

wrm:
  scheduling:
    algorithm: FIFO
    type-mode: full_time





spring:
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      root: INFO




