# application.yml
wrm:
  scheduling:
    algorithm: FIFO





spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/wrm
    username: yassir
    password: User_Password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
