spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/dev_db
#    username: postgres
#    password: User_Password
#    driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5431/wrm
      username: yassir
      password: User_Password
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: DEBUG
