spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sit_db
    username: sit_user
    password: sit_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
  logging:
    level:
      root: INFO
