wrm:
  scheduling:
    algorithm: FIFO
    type-mode: full_time





spring:
  profiles:
    active: uat
  datasource:
    url: jdbc:postgresql://localhost:5431/wrm
    username: yassir
    password: User_Password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      root: INFO




